name: "RC Branch Created"

on:
  workflow_dispatch:

jobs:
  setup-rc:
    if: github.ref_type == "branch"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: RC branch detected
        run: |
          echo "New RC branch: ${{ github.ref }}"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Semantic Release
        uses: ./.github/workflows/semantic-release
        with:
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
